name: dicoding_submission
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0
  json_serializable: ^2.0.0
  http: ^0.12.0+1
  curved_navigation_bar: ^0.2.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - data_local/meals_breakfast.json
    - data_local/meals_desert.json
    - assets/desert/52767.jpg
    - assets/desert/52768.jpg
    - assets/desert/52776.jpg
    - assets/desert/52853.jpg
    - assets/desert/52855.jpg
    - assets/desert/52856.jpg
    - assets/desert/52858.jpg
    - assets/desert/52890.jpg
    - assets/desert/52893.jpg
    - assets/desert/52894.jpg
    - assets/desert/52897.jpg
    - assets/desert/52898.jpg
    - assets/desert/52909.jpg
    - assets/desert/52923.jpg
    - assets/desert/52928.jpg
    - assets/desert/52961.jpg
    - assets/breakfast/52771.jpg
    - assets/breakfast/52785.jpg
    - assets/breakfast/52807.jpg
    - assets/breakfast/52816.jpg
    - assets/breakfast/52829.jpg
    - assets/breakfast/52835.jpg
    - assets/breakfast/52844.jpg
    - assets/breakfast/52864.jpg
    - assets/breakfast/52866.jpg
    - assets/breakfast/52870.jpg
    - assets/breakfast/52871.jpg
    - assets/breakfast/52872.jpg
    - assets/breakfast/52906.jpg
    - assets/breakfast/52908.jpg
    - assets/breakfast/52911.jpg
    - assets/breakfast/52955.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
